# Generated by Django 4.2.1 on 2024-09-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_url_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.IntegerField(default=0)),
                ('duplicate', models.IntegerField(default=0)),
                ('whitelisted', models.IntegerField(default=0)),
                ('invalid_url', models.IntegerField(default=0)),
                ('meta_new', models.IntegerField(default=0)),
                ('meta_deplicate', models.IntegerField(default=0)),
                ('meta_invalid', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
