# Generated by Django 4.2.1 on 2023-05-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_whitelist',
            name='added_by',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
