# Generated by Django 4.2.1 on 2023-05-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_whitelist',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtube.client'),
            preserve_default=False,
        ),
    ]
