# Generated by Django 4.2.1 on 2023-05-08 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0004_youtube_whitelist_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_whitelist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='youtube_whitelist',
            name='channel_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
