# Generated by Django 4.2.1 on 2023-05-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0007_alter_youtube_whitelist_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_whitelist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
