# Generated by Django 4.2.1 on 2023-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_alter_youtube_whitelist_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_whitelist',
            name='channel_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
