# Generated by Django 4.2.1 on 2023-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_user_url_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_url_report',
            name='invalid_url',
            field=models.IntegerField(default=0),
        ),
    ]
