# Generated by Django 4.2.1 on 2023-05-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_user_url_report_invalid_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_url_model',
            name='video_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
