# Generated by Django 4.2.1 on 2023-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_alter_youtube_url_model_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_whitelist',
            name='channel_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
