# Generated by Django 4.2.1 on 2023-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0014_alter_youtube_whitelist_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
