# Generated by Django 4.2.1 on 2023-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_alter_client_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_whitelist',
            name='channel_url',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
