# Generated by Django 4.2.1 on 2023-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0017_youtube_url_model_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_url_model',
            name='content_duration',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
